{% set name = "mockito" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kaste/mockito-python/archive/{{ version }}.tar.gz
  sha256: 5d8b65e0eb1573b38a18cd31c8ad70114baa9da4970c6072104de93c543416d3

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - python
    - hatchling
    - hatch-vcs
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - mockito
  requires:
    - pip
    - pytest
    - numpy
  commands:
    - pip check
    - pytest tests
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"

about:
  home: https://github.com/kaste/mockito-python
  summary: Mockito is a spying framework originally based on the Java library with the same name.
  description: |
    Mockito is a spying framework originally based on the Java library with the same name.
    (Actually we invented the strict stubbing mode back in 2009.)
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/kaste/mockito-python
  doc_url: https://mockito-python.readthedocs.io

extra:
  recipe-maintainers:
    - vnlitvinov
