{% set name = "mockito" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kaste/mockito-python/archive/{{ version }}.tar.gz
  sha256: fe0614d07bf0f762f9b0e7b7183788e80941950315f58dfa2d405415afc9e65a

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python

test:
  imports:
    - mockito
  requires:
    - pip
    - pytest
    - numpy
  source_files:
    - tests/
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/kaste/mockito-python
  summary: Mockito is a spying framework.
  description: Mockito is a spying framework originally based on the Java library with the same name.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/kaste/mockito-python
  doc_url: https://mockito-python.readthedocs.io

extra:
  recipe-maintainers:
    - vnlitvinov
